P = {('p6', 'p8'): ('p6', 'p8', ('p8', 'p3'), ('p8', 'p4')), 
('p7', 'p2'): ('p7', 'p2', None, None), 
('p6', 'p7'): ('p6', 'p7', ('p7', 'p1'), ('p7', 'p2')), 
('p8', 'p4'): ('p8', 'p4', None, None), 
('p8', 'p3'): ('p8', 'p3', None, None), 
'pTop': ('Top', 'p6', ('p6', 'p7'), ('p6', 'p8')), 
('p7', 'p1'): ('p7', 'p1', None, None)}


fDTL = {('p8', 'h2'): [['T', ('p3', 'h2'), ('p4', 'h4'), 1], 1], 
('p7', 'h1'): [['T', ('p1', 'h1'), ('p2', 'h3'), 1], 1], 
('p1', 'h1'): [['C', (None, None), (None, None), 1], 0], 
('p6', 'h7'): [['S', ('p7', 'h1'), ('p8', 'h2'), 1], 2], 
('p3', 'h2'): [['C', (None, None), (None, None), 1], 0], 
('p8', 'h4'): [['T', ('p4', 'h4'), ('p3', 'h2'), 1], 1], 
('p2', 'h3'): [['C', (None, None), (None, None), 1], 0], 
('p6', 'h8'): [['S', ('p7', 'h3'), ('p8', 'h4'), 1], 2], 
('p7', 'h3'): [['T', ('p2', 'h3'), ('p1', 'h1'), 1], 1], 
('p4', 'h4'): [['C', (None, None), (None, None), 1], 0]}



newDTL =          
#from June16:
{('p8', 'h2'): [['T', ('p3', 'h2'), ('p4', 'h4'), 0], 1], 
('p6', 'h7'): [['S', ('p7', 'h1'), ('p8', 'h2'), 1], 2], 
('p3', 'h2'): [['C', (None, None), (None, None), 0], 0], 
('p8', 'h4'): [['T', ('p4', 'h4'), ('p3', 'h2'), 1], 1], 
('p2', 'h3'): [['C', (None, None), (None, None), 0], 0], 
('p7', 'h3'): [['T', ('p2', 'h3'), ('p1', 'h1'), 1], 1], 
('p7', 'h1'): [['T', ('p1', 'h1'), ('p2', 'h3'), 0], 1], 
('p1', 'h1'): [['C', (None, None), (None, None), 0], 0], 
('p6', 'h8'): [['S', ('p7', 'h3'), ('p8', 'h4'), 1], 2], 
('p4', 'h4'): [['C', (None, None), (None, None), 0], 0]}



bookkeeping output
'BSFHMap:'

{('p8', 'h2'): [['T', ('p3', 'h2'), ('p4', 'h4'), 1], 3], 
('p7', 'h3'): [['T', ('p2', 'h3'), ('p1', 'h1'), 1], 3], 
('p7', 'h1'): [['T', ('p1', 'h1'), ('p2', 'h3'), 1], 3], 
('p1', 'h1'): [['C', (None, None), (None, None), 1], 1], 
('p6', 'h7'): [['S', ('p7', 'h1'), ('p8', 'h2'), 1], 7], 
('p3', 'h2'): [['C', (None, None), (None, None), 1], 1], 
('p8', 'h4'): [['T', ('p4', 'h4'), ('p3', 'h2'), 1], 3], 
('p2', 'h3'): [['C', (None, None), (None, None), 1], 1], 
('p6', 'h8'): [['S', ('p7', 'h3'), ('p8', 'h4'), 1], 7], 
('p4', 'h4'): [['C', (None, None), (None, None), 1], 1]}



we did it!!!!!

[{('p8', 'h2'): ('T', ('p3', 'h2'), ('p4', 'h4')), 
('p7', 'h1'): ('T', ('p1', 'h1'), ('p2', 'h3')), 
('p1', 'h1'): ('C', (None, None), (None, None)), 
'p6', 'h7'): ('S', ('p7', 'h1'), ('p8', 'h2')), 
('p3', 'h2'): ('C', (None, None), (None, None)), 
('p2', 'h3'): ('C', (None, None), (None, None)), 
('p4', 'h4'): ('C', (None, None), (None, None))}, 

{('p7', 'h3'): ('T', ('p2', 'h3'), ('p1', 'h1')), 
('p1', 'h1'): ('C', (None, None), (None, None)), 
('p3', 'h2'): ('C', (None, None), (None, None)), 
('p8', 'h4'): ('T', ('p4', 'h4'), ('p3', 'h2')), 
('p2', 'h3'): ('C', (None, None), (None, None)), 
('p6', 'h8'): ('S', ('p7', 'h3'), ('p8', 'h4')), 
('p4', 'h4'): ('C', (None, None), (None, None))}]


 bookkeeping(newDTL, P):
 {('p8', 'h2'): [('T', ('p3', 'h2'), ('p4', 'h4'), 0), 0], 
 ('p7', 'h1'): [('T', ('p1', 'h1'), ('p2', 'h3'), 0), 0], 
 ('p1', 'h1'): [('C', (None, None), (None, None), 0), 0], 
 ('p6', 'h7'): [('S', ('p7', 'h1'), ('p8', 'h2'), 0), 0], 
 ('p3', 'h2'): [('C', (None, None), (None, None), 0), 0], 
 ('p8', 'h4'): [('T', ('p4', 'h4'), ('p3', 'h2'), 1), 1], 
 ('p2', 'h3'): [('C', (None, None), (None, None), 0), 0], 
 ('p6', 'h8'): [('S', ('p7', 'h3'), ('p8', 'h4'), 1), 3], 
 ('p7', 'h3'): [('T', ('p2', 'h3'), ('p1', 'h1'), 1), 1], 
 ('p4', 'h4'): [('C', (None, None), (None, None), 0), 0]}


testing from heliconius tree
H = {('m5', 'ecuadoriensis_EastE'): ('m5', 'ecuadoriensis_EastE', None, None), 
('m9', 'm10'): ('m9', 'm10', ('m10', 'melpomene_WestPA'), ('m10', 'rosina_WestCR')), 
('m2', 'm3'): ('m2', 'm3', ('m3', 'm4'), ('m3', 'm5')), 
('m1', 'm8'): ('m1', 'm8', ('m8', 'm9'), ('m8', 'm11')), 
('m7', 'thelxiopeia_EastFG'): ('m7', 'thelxiopeia_EastFG', None, None), 
('m6', 'm7'): ('m6', 'm7', ('m7', 'thelxiopeia_EastFG'), ('m7', 'melpomene_EastFG')), 
('m3', 'm5'): ('m3', 'm5', ('m5', 'ecuadoriensis_EastE'), ('m5', 'malleti_EastE')), 
'hTop': ('Top', 'm1', ('m1', 'm2'), ('m1', 'm8')), 
('m9', 'rosina_WestPA'): ('m9', 'rosina_WestPA', None, None), 
('m11', 'cythera_WestE'): ('m11', 'cythera_WestE', None, None), 
('m8', 'm9'): ('m8', 'm9', ('m9', 'm10'), ('m9', 'rosina_WestPA')), 
('m10', 'melpomene_WestPA'): ('m10', 'melpomene_WestPA', None, None), 
('m10', 'rosina_WestCR'): ('m10', 'rosina_WestCR', None, None), 
('m3', 'm4'): ('m3', 'm4', ('m4', 'aglaope_EastPE'), ('m4', 'amaryllis_EastPE')), 
('m5', 'malleti_EastE'): ('m5', 'malleti_EastE', None, None), 
('m4', 'aglaope_EastPE'): ('m4', 'aglaope_EastPE', None, None), 
('m11', 'melpomene_EastC'): ('m11', 'melpomene_EastC', None, None), 
('m7', 'melpomene_EastFG'): ('m7', 'melpomene_EastFG', None, None), 
('m2', 'm6'): ('m2', 'm6', ('m6', 'm7'), ('m6', 'melpomene_EastT')), 
('m1', 'm2'): ('m1', 'm2', ('m2', 'm3'), ('m2', 'm6')), 
('m4', 'amaryllis_EastPE'): ('m4', 'amaryllis_EastPE', None, None), 
('m6', 'melpomene_EastT'): ('m6', 'melpomene_EastT', None, None), 
('m8', 'm11'): ('m8', 'm11', ('m11', 'melpomene_EastC'), ('m11', 'cythera_WestE'))}

P = {('n10', 'hydara_WestPA'): ('n10', 'hydara_WestPA', None, None), 
('n6', 'erato_EastFG'): ('n6', 'erato_EastFG', None, None), 
('n5', 'etylus_EastE'): ('n5', 'etylus_EastE', None, None), 
('n9', 'n10'): ('n9', 'n10', ('n10', 'hydara_EastT'), ('n10', 'hydara_WestPA')), 
('n2', 'n6'): ('n2', 'n6', ('n6', 'erato_EastFG'), ('n6', 'hydara_EastFG')), 
('n6', 'hydara_EastFG'): ('n6', 'hydara_EastFG', None, None), 
('n9', 'petiverana_WestCR'): ('n9', 'petiverana_WestCR', None, None), 
('n1', 'n2'): ('n1', 'n2', ('n2', 'n3'), ('n2', 'n6')), 
('n2', 'n3'): ('n2', 'n3', ('n3', 'n4'), ('n3', 'lativitta_EastE')), 
('n7', 'n8'): ('n7', 'n8', ('n8', 'n9'), ('n8', 'petiverana_WestPA')), 
'pTop': ('Top', 'n1', ('n1', 'n2'), ('n1', 'n7')), 
('n8', 'petiverana_WestPA'): ('n8', 'petiverana_WestPA', None, None), 
('n7', 'n11'): ('n7', 'n11', ('n11', 'hydara_EastC'), ('n11', 'cyrbia_WestE')), 
('n10', 'hydara_EastT'): ('n10', 'hydara_EastT', None, None), 
('n1', 'n7'): ('n1', 'n7', ('n7', 'n8'), ('n7', 'n11')), 
('n4', 'n5'): ('n4', 'n5', ('n5', 'favorinus_EastPE'), ('n5', 'etylus_EastE')), 
('n3', 'lativitta_EastE'): ('n3', 'lativitta_EastE', None, None), 
('n8', 'n9'): ('n8', 'n9', ('n9', 'n10'), ('n9', 'petiverana_WestCR')), 
('n4', 'emma_EastPE'): ('n4', 'emma_EastPE', None, None), 
('n11', 'hydara_EastC'): ('n11', 'hydara_EastC', None, None), 
('n11', 'cyrbia_WestE'): ('n11', 'cyrbia_WestE', None, None), 
('n5', 'favorinus_EastPE'): ('n5', 'favorinus_EastPE', None, None), 
('n3', 'n4'): ('n3', 'n4', ('n4', 'emma_EastPE'), ('n4', 'n5'))}

phi = {'cyrbia_WestE': 'cythera_WestE', 
'erato_EastFG': 'thelxiopeia_EastFG', 
'hydara_EastFG': 'melpomene_EastFG', 
'lativitta_EastE': 'malleti_EastE', 
'hydara_EastC': 'melpomene_EastC', 
'petiverana_WestPA': 'rosina_WestPA', 
'petiverana_WestCR': 'rosina_WestCR', 
'emma_EastPE': 'aglaope_EastPE', 
'etylus_EastE': 'ecuadoriensis_EastE', 
'favorinus_EastPE': 'amaryllis_EastPE', 
'hydara_EastT': 'melpomene_EastT', 
'hydara_WestPA': 'melpomene_WestPA'}

DPJune12: 
Heliconius:
DTL = {('petiverana_WestCR', 'rosina_WestCR'): [['C', (None, None), (None, None), 1], 0], 
('n2', 'm2'): [['S', ('n3', 'm3'), ('n6', 'm6'), 1], 3], 
('n8', 'm9'): [['S', ('n9', 'm10'), ('petiverana_WestPA', 'rosina_WestPA'), 1], 1], 
('emma_EastPE', 'aglaope_EastPE'): [['C', (None, None), (None, None), 1], 0], 
('favorinus_EastPE', 'amaryllis_EastPE'): [['C', (None, None), (None, None), 1], 0], 
('etylus_EastE', 'ecuadoriensis_EastE'): [['C', (None, None), (None, None), 1], 0], 
('lativitta_EastE', 'malleti_EastE'): [['C', (None, None), (None, None), 1], 0], 
('n6', 'm7'): [['S', ('erato_EastFG', 'thelxiopeia_EastFG'), ('hydara_EastFG', 'melpomene_EastFG'), 1], 0], 
('n10', 'melpomene_WestPA'): [['T', ('hydara_WestPA', 'melpomene_WestPA'), ('hydara_EastT', 'melpomene_EastT'), 1], 1], 
('hydara_WestPA', 'melpomene_WestPA'): [['C', (None, None), (None, None), 1], 0], 
('n6', 'm6'): [['L', ('n6', 'm7'), (None, None), 1], 1], 
('petiverana_WestPA', 'rosina_WestPA'): [['C', (None, None), (None, None), 1], 0], 
('n7', 'm8'): [['S', ('n8', 'm9'), ('n11', 'm11'), 1], 1], 
('cyrbia_WestE', 'cythera_WestE'): [['C', (None, None), (None, None), 1], 0], 
('hydara_EastT', 'melpomene_EastT'): [['C', (None, None), (None, None), 1], 0], 
('erato_EastFG', 'thelxiopeia_EastFG'): [['C', (None, None), (None, None), 1], 0], 
('n5', 'amaryllis_EastPE'): [['T', ('favorinus_EastPE', 'amaryllis_EastPE'), ('etylus_EastE', 'ecuadoriensis_EastE'), 1], 1], 
('n11', 'm11'): [['S', ('hydara_EastC', 'melpomene_EastC'), ('cyrbia_WestE', 'cythera_WestE'), 1], 0], 
('n9', 'm10'): [['S', ('n10', 'melpomene_WestPA'), ('petiverana_WestCR', 'rosina_WestCR'), 1], 1], 
('n3', 'm3'): [['S', ('n4', 'm4'), ('lativitta_EastE', 'm5'), 1], 2], 
('n4', 'm4'): [['S', ('emma_EastPE', 'aglaope_EastPE'), ('n5', 'amaryllis_EastPE'), 1], 1], 
('hydara_EastC', 'melpomene_EastC'): [['C', (None, None), (None, None), 1], 0], 
('n1', 'm1'): [['S', ('n2', 'm2'), ('n7', 'm8'), 1], 4], 
('hydara_EastFG', 'melpomene_EastFG'): [['C', (None, None), (None, None), 1], 0], 
('lativitta_EastE', 'm5'): [['L', ('lativitta_EastE', 'malleti_EastE'), (None, None), 1], 1]}

vidua:
H = {('h0', 'h1'): ('h0', 'h1', ('h1', 'O._atricolis'), ('h1', 'A._subflava')), 
('h91', 'L._senegala_rhodopsis'): ('h91', 'L._senegala_rhodopsis', None, None), 
('h49', 'h50'): ('h49', 'h50', ('h50', 'C._quartinia'), ('h50', 'C._melanotis')), 
('h1', 'O._atricolis'): ('h1', 'O._atricolis', None, None), 
('h68', 'h71'): ('h68', 'h71', ('h71', 'H._niveoguttatus'), ('h71', 'H._margaritatus')), 
('h101', 'L._virata'): ('h101', 'L._virata', None, None), 
('h91', 'L._senegala_rendalii'): ('h91', 'L._senegala_rendalii', None, None), 
('h69', 'h74'): ('h69', 'h74', ('h74', 'C._monteiri'), ('h74', 'h87')), 
('h51', 'h54'): ('h51', 'h54', ('h54', 'E._astrild'), ('h54', 'h57')), 
('h89', 'h90'): ('h89', 'h90', ('h90', 'L._rufopicta'), ('h90', 'L._nitidula')), 
('h100', 'L._r._rubricata'): ('h100', 'L._r._rubricata', None, None), 
('h50', 'C._melanotis'): ('h50', 'C._melanotis', None, None), 
('h0', 'h2'): ('h0', 'h2', ('h2', 'h48'), ('h2', 'h49')), 
('h49', 'h51'): ('h49', 'h51', ('h51', 'h54'), ('h51', 'E._erythronotos')), 
('h76', 'P._melba_grotei'): ('h76', 'P._melba_grotei', None, None), 
('h76', 'P._melba_citerior'): ('h76', 'P._melba_citerior', None, None), 
('h75', 'h77'): ('h75', 'h77', ('h77', 'P._afra'), ('h77', 'h81')), 
('h75', 'h76'): ('h75', 'h76', ('h76', 'P._melba_grotei'), ('h76', 'P._melba_citerior')), 
('h69', 'h75'): ('h69', 'h75', ('h75', 'h76'), ('h75', 'h77')), 
'hTop': ('Top', 'h0', ('h0', 'h1'), ('h0', 'h2')), 
('h89', 'h91'): ('h89', 'h91', ('h91', 'L._senegala_rendalii'), ('h91', 'L._senegala_rhodopsis')), 
('h61', 'E._melpoda'): ('h61', 'E._melpoda', None, None), 
('h83', 'P._hypogrammica'): ('h83', 'P._hypogrammica', None, None), 
('h90', 'L._rufopicta'): ('h90', 'L._rufopicta', None, None), 
('h54', 'E._astrild'): ('h54', 'E._astrild', None, None), 
('h87', 'h88'): ('h87', 'h88', ('h88', 'L._larvata'), ('h88', 'h97')), 
('h97', 'h99'): ('h97', 'h99', ('h99', 'h100'), ('h99', 'h101')), 
('h88', 'h97'): ('h88', 'h97', ('h97', 'L._rara'), ('h97', 'h99')), 
('h48', 'h64'): ('h48', 'h64', ('h64', 'G._ianthinogaster'), ('h64', 'G._granatia')), 
('h59', 'E._rhodophyga'): ('h59', 'E._rhodophyga', None, None), 
('h74', 'h87'): ('h74', 'h87', ('h87', 'h88'), ('h87', 'h89')), 
('h65', 'h69'): ('h65', 'h69', ('h69', 'h74'), ('h69', 'h75')), 
('h71', 'H._margaritatus'): ('h71', 'H._margaritatus', None, None), 
('h51', 'E._erythronotos'): ('h51', 'E._erythronotos', None, None), 
('h64', 'G._granatia'): ('h64', 'G._granatia', None, None), 
('h87', 'h89'): ('h87', 'h89', ('h89', 'h90'), ('h89', 'h91')), 
('h50', 'C._quartinia'): ('h50', 'C._quartinia', None, None), 
('h2', 'h49'): ('h2', 'h49', ('h49', 'h50'), ('h49', 'h51')), 
('h64', 'G._ianthinogaster'): ('h64', 'G._ianthinogaster', None, None), 
('h99', 'h100'): ('h99', 'h100', ('h100', 'L._r_cingica'), ('h100', 'L._r._rubricata')), 
('h54', 'h57'): ('h54', 'h57', ('h57', 'E._paludicola'), ('h57', 'h59')), 
('h74', 'C._monteiri'): ('h74', 'C._monteiri', None, None), 
('h48', 'h65'): ('h48', 'h65', ('h65', 'h68'), ('h65', 'h69')), 
('h71', 'H._niveoguttatus'): ('h71', 'H._niveoguttatus', None, None), 
('h59', 'h61'): ('h59', 'h61', ('h61', 'E._troglodytes'), ('h61', 'E._melpoda')), 
('h65', 'h68'): ('h65', 'h68', ('h68', 'E._dybowskii'), ('h68', 'h71')), 
('h77', 'P._afra'): ('h77', 'P._afra', None, None), 
('h97', 'L._rara'): ('h97', 'L._rara', None, None), 
('h61', 'E._troglodytes'): ('h61', 'E._troglodytes', None, None), 
('h77', 'h81'): ('h77', 'h81', ('h81', 'P._lineata'), ('h81', 'h83')), 
('h57', 'h59'): ('h57', 'h59', ('h59', 'E._rhodophyga'), ('h59', 'h61')), 
('h81', 'P._lineata'): ('h81', 'P._lineata', None, None), 
('h83', 'P._phoenicoptera'): ('h83', 'P._phoenicoptera', None, None), 
('h2', 'h48'): ('h2', 'h48', ('h48', 'h64'), ('h48', 'h65')), 
('h1', 'A._subflava'): ('h1', 'A._subflava', None, None), 
('h105', 'L._sanguinodorsalis'): ('h105', 'L._sanguinodorsalis', None, None), 
('h81', 'h83'): ('h81', 'h83', ('h83', 'P._phoenicoptera'), ('h83', 'P._hypogrammica')), 
('h105', 'L._rhodopareia'): ('h105', 'L._rhodopareia', None, None), 
('h99', 'h101'): ('h99', 'h101', ('h101', 'L._virata'), ('h101', 'h105')), 
('h90', 'L._nitidula'): ('h90', 'L._nitidula', None, None), 
('h88', 'L._larvata'): ('h88', 'L._larvata', None, None), 
('h101', 'h105'): ('h101', 'h105', ('h105', 'L._rhodopareia'), ('h105', 'L._sanguinodorsalis')), 
('h100', 'L._r_cingica'): ('h100', 'L._r_cingica', None, None), 
('h57', 'E._paludicola'): ('h57', 'E._paludicola', None, None), 
('h68', 'E._dybowskii'): ('h68', 'E._dybowskii', None, None)}

P = {('p4', 'p6'): ('p4', 'p6', ('p6', 'V._fischeri'), ('p6', 'V._regia')), 
('p5', 'V._hypocherina'): ('p5', 'V._hypocherina', None, None), 
('p6', 'V._regia'): ('p6', 'V._regia', None, None), 
('p7', 'p10'): ('p7', 'p10', ('p10', 'p12'), ('p10', 'p13')), 
('p33', 'p37'): ('p33', 'p37', ('p37', 'V._interjecta'), ('p37', 'V._togoensis')), 
('p15', 'V._wilsoni'): ('p15', 'V._wilsoni', None, None), 
('p107', 'V._chalybeata_S.'): ('p107', 'V._chalybeata_S.', None, None), 
('p6', 'V._fischeri'): ('p6', 'V._fischeri', None, None), 
('p5', 'p26'): ('p5', 'p26', ('p26', 'p28'), ('p26', 'p29')), 
('p28', 'p33'): ('p28', 'p33', ('p33', 'V._orientalis'), ('p33', 'p37')), 
('p118', 'V._nigeriae'): ('p118', 'V._nigeriae', None, None), 
('p13', 'p21'): ('p13', 'p21', ('p21', 'V._purpurascens'), ('p21', 'p107')), 
('p12', 'p15'): ('p12', 'p15', ('p15', 'p116'), ('p15', 'V._wilsoni')), 
('p4', 'p7'): ('p4', 'p7', ('p7', 'p10'), ('p7', 'V._chalybeata_W.')), 
('p37', 'V._togoensis'): ('p37', 'V._togoensis', None, None), 
('p26', 'p28'): ('p26', 'p28', ('p28', 'p32'), ('p28', 'p33')), 
'pTop': ('Top', 'p3', ('p3', 'p4'), ('p3', 'p5')), 
('p32', 'V._obtusa'): ('p32', 'V._obtusa', None, None), 
('p28', 'p32'): ('p28', 'p32', ('p32', 'V._paradisaea'), ('p32', 'V._obtusa')), 
('p3', 'p5'): ('p3', 'p5', ('p5', 'p26'), ('p5', 'V._hypocherina')), 
('p29', 'V._macroura_W.'): ('p29', 'V._macroura_W.', None, None), 
('p7', 'V._chalybeata_W.'): ('p7', 'V._chalybeata_W.', None, None), 
('p116', 'V._larvaticola'): ('p116', 'V._larvaticola', None, None), 
('p120', 'V._camerunensis'): ('p120', 'V._camerunensis', None, None), 
('p10', 'p12'): ('p10', 'p12', ('p12', 'p118'), ('p12', 'p15')), 
('p116', 'p120'): ('p116', 'p120', ('p120', 'V._camerunensis'), ('p120', 'V._maryae')), 
('p26', 'p29'): ('p26', 'p29', ('p29', 'V._macroura_S'), ('p29', 'V._macroura_W.')), 
('p32', 'V._paradisaea'): ('p32', 'V._paradisaea', None, None), 
('p21', 'p107'): ('p21', 'p107', ('p107', 'V._chalybeata_S.'), ('p107', 'V._codringtoni')), 
('p15', 'p116'): ('p15', 'p116', ('p116', 'p120'), ('p116', 'V._larvaticola')), 
('p3', 'p4'): ('p3', 'p4', ('p4', 'p6'), ('p4', 'p7')), 
('p37', 'V._interjecta'): ('p37', 'V._interjecta', None, None), 
('p33', 'V._orientalis'): ('p33', 'V._orientalis', None, None), 
('p10', 'p13'): ('p10', 'p13', ('p13', 'V._funera'), ('p13', 'p21')), 
('p120', 'V._maryae'): ('p120', 'V._maryae', None, None), 
('p12', 'p118'): ('p12', 'p118', ('p118', 'V._nigeriae'), ('p118', 'V._raricola')), 
('p107', 'V._codringtoni'): ('p107', 'V._codringtoni', None, None), 
('p21', 'V._purpurascens'): ('p21', 'V._purpurascens', None, None), 
('p13', 'V._funera'): ('p13', 'V._funera', None, None), 
('p118', 'V._raricola'): ('p118', 'V._raricola', None, None), 
('p29', 'V._macroura_S'): ('p29', 'V._macroura_S', None, None)}

phi = {'V._chalybeata_W.': 'L._senegala_rhodopsis', 'V._orientalis': 'P._melba_citerior', 
'V._raricola': 'A._subflava', 'V._macroura_S': 'E._astrild', 'V._togoensis': 'P._hypogrammica', 
'V._codringtoni': 'H._niveoguttatus', 'V._funera': 'L._r._rubricata', 'V._regia': 'G._granatia', 
'V._camerunensis': 'L._rara', 'V._chalybeata_S.': 'L._senegala_rendalii', 'V._macroura_W.': 'E._melpoda', 
'V._nigeriae': 'O._atricolis', 'V._interjecta': 'P._phoenicoptera', 'V._wilsoni': 'L._rufopicta', 
'V._hypocherina': 'E._erythronotos', 'V._obtusa': 'P._afra', 'V._purpurascens': 'L._rhodopareia', 
'V._paradisaea': 'P._melba_grotei', 'V._fischeri': 'G._ianthinogaster', 'V._maryae': 'L._sanguinodorsalis', 
'V._larvaticola': 'C._monteiri'}

DTL = {('V._fischeri', 'G._ianthinogaster'): [['C', (None, None), (None, None), 49.0], 0], 
('p33', 'P._melba_citerior'): [['T', ('V._orientalis', 'P._melba_citerior'), ('p37', 'h83'), 115.0], 1], 
('p4', 'h64'): [['T', ('p6', 'h64'), ('p7', 'h105'), 20.0], 9], 
('p29', 'h54'): [['L', ('p29', 'E._astrild'), (None, None), 13.0], 2], 
('p116', 'C._monteiri'): [['T', ('V._larvaticola', 'C._monteiri'), ('p120', 'L._rara'), 9.0], 2], 
('V._funera', 'L._r._rubricata'): [['C', (None, None), (None, None), 49.0], 0], 
('p13', 'L._rhodopareia'): [['T', ('p21', 'L._rhodopareia'), ('V._funera', 'L._r._rubricata'), 34.0], 3], 
('p26', 'h76'): [['T', ('p28', 'h76'), ('p29', 'E._astrild'), 17.0], 4], 
('p10', 'L._senegala_rendalii'): [['T', ('p13', 'L._senegala_rendalii'), ('p12', 'h1'), 3.0], ['T', ('p13', 'L._senegala_rendalii'), ('p12', 'C._monteiri'), 3.0], ['T', ('p13', 'L._senegala_rendalii'), ('p12', 'L._rara'), 3.0], ['T', ('p13', 'L._senegala_rendalii'), ('p12', 'L._rufopicta'), 6.0], 8], 
('p3', 'E._astrild'): [['T', ('p5', 'E._astrild'), ('p4', 'h64'), 2.0], 15], 
('V._nigeriae', 'O._atricolis'): [['C', (None, None), (None, None), 49.0], 0], 
('V._chalybeata_W.', 'L._senegala_rhodopsis'): [['C', (None, None), (None, None), 49.0], 0], 
('p5', 'E._melpoda'): [['T', ('p26', 'E._melpoda'), ('V._hypocherina', 'E._erythronotos'), 2.0], 5], 
('p107', 'L._senegala_rendalii'): [['T', ('V._chalybeata_S.', 'L._senegala_rendalii'), ('V._codringtoni', 'H._niveoguttatus'), 32.0], 1], 
('p116', 'L._sanguinodorsalis'): [['T', ('p120', 'L._sanguinodorsalis'), ('V._larvaticola', 'C._monteiri'), 34.0], 2], 
('p15', 'L._rufopicta'): [['T', ('V._wilsoni', 'L._rufopicta'), ('p116', 'C._monteiri'), 3.0], ['T', ('V._wilsoni', 'L._rufopicta'), ('p116', 'L._rara'), 3.0], 3], 
('p21', 'L._rhodopareia'): [['T', ('V._purpurascens', 'L._rhodopareia'), ('p107', 'H._niveoguttatus'), 17.0], ['T', ('V._purpurascens', 'L._rhodopareia'), ('p107', 'L._senegala_rendalii'), 17.0], 2], 
('V._raricola', 'A._subflava'): [['C', (None, None), (None, None), 49.0], 0], 
('V._togoensis', 'P._hypogrammica'): [['C', (None, None), (None, None), 213.0], 0], 
('p3', 'h51'): [['T', ('p5', 'h51'), ('p4', 'h64'), 4.0], 15], 
('V._interjecta', 'P._phoenicoptera'): [['C', (None, None), (None, None), 213.0], 0], 
('p5', 'h51'): [['S', ('p26', 'h54'), ('V._hypocherina', 'E._erythronotos'), 26.0], 5], 
('p3', 'E._melpoda'): [['T', ('p5', 'E._melpoda'), ('p4', 'h64'), 2.0], 15], 
('V._camerunensis', 'L._rara'): [['C', (None, None), (None, None), 49.0], 0], 
('p26', 'h54'): [['T', ('p29', 'h54'), ('p28', 'h76'), 13.0], ['L', ('p26', 'E._astrild'), (None, None), 13.0], 5], 
('V._wilsoni', 'L._rufopicta'): [['C', (None, None), (None, None), 49.0], 0], 
('p3', 'h105'): [['T', ('p4', 'h105'), ('p5', 'h51'), 4.0], ['T', ('p4', 'h105'), ('p5', 'h76'), 2.0], 15], 
('p7', 'h91'): [['S', ('p10', 'L._senegala_rendalii'), ('V._chalybeata_W.', 'L._senegala_rhodopsis'), 15.0], 8], 
('p29', 'E._melpoda'): [['T', ('V._macroura_W.', 'E._melpoda'), ('V._macroura_S', 'E._astrild'), 2.0], 1], 
('p120', 'L._rara'): [['T', ('V._camerunensis', 'L._rara'), ('V._maryae', 'L._sanguinodorsalis'), 15.0], 1], 
('p32', 'P._melba_grotei'): [['T', ('V._paradisaea', 'P._melba_grotei'), ('V._obtusa', 'P._afra'), 115.0], 1], 
('p7', 'L._senegala_rhodopsis'): [['T', ('V._chalybeata_W.', 'L._senegala_rhodopsis'), ('p10', 'h105'), 6.0], 8], 
('p13', 'L._senegala_rendalii'): [['T', ('p21', 'L._senegala_rendalii'), ('V._funera', 'L._r._rubricata'), 15.0], 3], 
('V._hypocherina', 'E._erythronotos'): [['C', (None, None), (None, None), 49.0], 0], 
('p29', 'E._astrild'): [['T', ('V._macroura_S', 'E._astrild'), ('V._macroura_W.', 'E._melpoda'), 64.0], 1], 
('V._codringtoni', 'H._niveoguttatus'): [['C', (None, None), (None, None), 49.0], 0], 
('p12', 'L._rufopicta'): [['T', ('p15', 'L._rufopicta'), ('p118', 'h1'), 6.0], 4], 
('p12', 'h1'): [['T', ('p118', 'h1'), ('p15', 'C._monteiri'), 3.0], 4], 
('V._macroura_S', 'E._astrild'): [['C', (None, None), (None, None), 130.0], 0], 
('p6', 'h64'): [['S', ('V._fischeri', 'G._ianthinogaster'), ('V._regia', 'G._granatia'), 49.0], 0], 
('V._chalybeata_S.', 'L._senegala_rendalii'): [['C', (None, None), (None, None), 49.0], 0], 
('p118', 'h1'): [['S', ('V._nigeriae', 'O._atricolis'), ('V._raricola', 'A._subflava'), 49.0], 0], 
('p28', 'h76'): [['S', ('p32', 'P._melba_grotei'), ('p33', 'P._melba_citerior'), 66.0], 2], 
('V._paradisaea', 'P._melba_grotei'): [['C', (None, None), (None, None), 164.0], 0], 
('p15', 'L._sanguinodorsalis'): [['T', ('p116', 'L._sanguinodorsalis'), ('V._wilsoni', 'L._rufopicta'), 34.0], 3], 
('p5', 'E._astrild'): [['T', ('p26', 'E._astrild'), ('V._hypocherina', 'E._erythronotos'), 2.0], 5], 
('p5', 'h76'): [['T', ('p26', 'h76'), ('V._hypocherina', 'E._erythronotos'), 15.0], 5], 
('p3', 'h91'): [['T', ('p4', 'h91'), ('p5', 'h51'), 10.0], ['T', ('p4', 'h91'), ('p5', 'h76'), 5.0], 15], 
('V._maryae', 'L._sanguinodorsalis'): [['C', (None, None), (None, None), 49.0], 0], 
('p10', 'h105'): [['S', ('p13', 'L._rhodopareia'), ('p12', 'L._sanguinodorsalis'), 34.0], 7], 
('p26', 'E._astrild'): [['T', ('p29', 'E._astrild'), ('p28', 'h76'), 17.0], 4], 
('p5', 'E._erythronotos'): [['T', ('V._hypocherina', 'E._erythronotos'), ('p26', 'h76'), 2.0], ['T', ('V._hypocherina', 'E._erythronotos'), ('p26', 'E._astrild'), 2.0], 5], 
('p4', 'h91'): [['T', ('p7', 'h91'), ('p6', 'h64'), 15.0], 9], 
('p3', 'E._erythronotos'): [['T', ('p5', 'E._erythronotos'), ('p4', 'h64'), 4.0], 15], 
('p15', 'C._monteiri'): [['T', ('p116', 'C._monteiri'), ('V._wilsoni', 'L._rufopicta'), 6.0], 3], 
('V._orientalis', 'P._melba_citerior'): [['C', (None, None), (None, None), 164.0], 0], 
('p12', 'L._rara'): [['T', ('p15', 'L._rara'), ('p118', 'h1'), 3.0], 4], 
('V._macroura_W.', 'E._melpoda'): [['C', (None, None), (None, None), 130.0], 0], 
('V._larvaticola', 'C._monteiri'): [['C', (None, None), (None, None), 49.0], 0], 
('p3', 'h76'): [['T', ('p5', 'h76'), ('p4', 'h64'), 2.0], ['T', ('p5', 'h76'), ('p4', 'h105'), 2.0], 15], 
('p107', 'H._niveoguttatus'): [['T', ('V._codringtoni', 'H._niveoguttatus'), ('V._chalybeata_S.', 'L._senegala_rendalii'), 17.0], 1], 
('p7', 'h105'): [['T', ('p10', 'h105'), ('V._chalybeata_W.', 'L._senegala_rhodopsis'), 28.0], 8], 
('p116', 'L._rara'): [['T', ('p120', 'L._rara'), ('V._larvaticola', 'C._monteiri'), 6.0], 2], 
('p120', 'L._sanguinodorsalis'): [['T', ('V._maryae', 'L._sanguinodorsalis'), ('V._camerunensis', 'L._rara'), 34.0], 1], 
('p21', 'L._senegala_rendalii'): [['T', ('p107', 'L._senegala_rendalii'), ('V._purpurascens', 'L._rhodopareia'), 15.0], 2], 
('p4', 'L._senegala_rhodopsis'): [['T', ('p7', 'L._senegala_rhodopsis'), ('p6', 'h64'), 6.0], 9], 
('V._obtusa', 'P._afra'): [['C', (None, None), (None, None), 164.0], 0], 
('V._regia', 'G._granatia'): [['C', (None, None), (None, None), 49.0], 0], 
('V._purpurascens', 'L._rhodopareia'): [['C', (None, None), (None, None), 49.0], 0], 
('p15', 'L._rara'): [['T', ('p116', 'L._rara'), ('V._wilsoni', 'L._rufopicta'), 3.0], 3], 
('p37', 'h83'): [['S', ('V._interjecta', 'P._phoenicoptera'), ('V._togoensis', 'P._hypogrammica'), 164.0], 0], 
('p26', 'E._melpoda'): [['T', ('p29', 'E._melpoda'), ('p28', 'h76'), 2.0], 4], 
('p12', 'C._monteiri'): [['T', ('p15', 'C._monteiri'), ('p118', 'h1'), 3.0], 4], 
('p3', 'L._senegala_rhodopsis'): [['T', ('p4', 'L._senegala_rhodopsis'), ('p5', 'h51'), 4.0], ['T', ('p4', 'L._senegala_rhodopsis'), ('p5', 'h76'), 2.0], 15], 
('p3', 'h64'): [['T', ('p4', 'h64'), ('p5', 'h51'), 4.0], ['T', ('p4', 'h64'), ('p5', 'h76'), 2.0], 15], 
('p4', 'h105'): [['T', ('p7', 'h105'), ('p6', 'h64'), 8.0], 9], 
('p12', 'L._sanguinodorsalis'): [['T', ('p15', 'L._sanguinodorsalis'), ('p118', 'h1'), 34.0], 4]}

Greedy output of vidua:
{('p33', 'P._melba_citerior'): ['T', ('V._orientalis', 'P._melba_citerior'), ('p37', 'h83')], 
('p4', 'h64'): ['T', ('p6', 'h64'), ('p7', 'h105')], 
('V._hypocherina', 'E._erythronotos'): ['C', (None, None), (None, None)], 
('V._funera', 'L._r._rubricata'): ['C', (None, None), (None, None)], 
('p13', 'L._rhodopareia'): ['T', ('p21', 'L._rhodopareia'), ('V._funera', 'L._r._rubricata')], 
('V._chalybeata_W.', 'L._senegala_rhodopsis'): ['C', (None, None), (None, None)], 
('p107', 'L._senegala_rendalii'): ['T', ('V._chalybeata_S.', 'L._senegala_rendalii'), ('V._codringtoni', 'H._niveoguttatus')], 
('p116', 'L._sanguinodorsalis'): ['T', ('p120', 'L._sanguinodorsalis'), ('V._larvaticola', 'C._monteiri')], 
('p21', 'L._rhodopareia'): ['T', ('V._purpurascens', 'L._rhodopareia'), ('p107', 'L._senegala_rendalii')], 
('V._raricola', 'A._subflava'): ['C', (None, None), (None, None)], 
('V._togoensis', 'P._hypogrammica'): ['C', (None, None), (None, None)], 
('p3', 'h51'): ['T', ('p5', 'h51'), ('p4', 'h64')], 
('V._interjecta', 'P._phoenicoptera'): ['C', (None, None), (None, None)], 
('p5', 'h51'): ['S', ('p26', 'h54'), ('V._hypocherina', 'E._erythronotos')], 
('V._camerunensis', 'L._rara'): ['C', (None, None), (None, None)], 
('p26', 'h54'): ['L', ('p26', 'E._astrild'), (None, None)], 
('V._wilsoni', 'L._rufopicta'): ['C', (None, None), (None, None)], 
('p32', 'P._melba_grotei'): ['T', ('V._paradisaea', 'P._melba_grotei'), ('V._obtusa', 'P._afra')], 
('p28', 'h76'): ['S', ('p32', 'P._melba_grotei'), ('p33', 'P._melba_citerior')], 
('p29', 'E._astrild'): ['T', ('V._macroura_S', 'E._astrild'), ('V._macroura_W.', 'E._melpoda')], 
('V._codringtoni', 'H._niveoguttatus'): ['C', (None, None), (None, None)], 
('p6', 'h64'): ['S', ('V._fischeri', 'G._ianthinogaster'), ('V._regia', 'G._granatia')], 
('V._chalybeata_S.', 'L._senegala_rendalii'): ['C', (None, None), (None, None)], 
('p118', 'h1'): ['S', ('V._nigeriae', 'O._atricolis'), ('V._raricola', 'A._subflava')], 
('V._macroura_S', 'E._astrild'): ['C', (None, None), (None, None)], 
('V._paradisaea', 'P._melba_grotei'): ['C', (None, None), (None, None)], 
('p15', 'L._sanguinodorsalis'): ['T', ('p116', 'L._sanguinodorsalis'), ('V._wilsoni', 'L._rufopicta')], 
('V._maryae', 'L._sanguinodorsalis'): ['C', (None, None), (None, None)], 
('p10', 'h105'): ['S', ('p13', 'L._rhodopareia'), ('p12', 'L._sanguinodorsalis')], 
('p26', 'E._astrild'): ['T', ('p29', 'E._astrild'), ('p28', 'h76')], 
('V._nigeriae', 'O._atricolis'): ['C', (None, None), (None, None)], 
('V._orientalis', 'P._melba_citerior'): ['C', (None, None), (None, None)], 
('V._macroura_W.', 'E._melpoda'): ['C', (None, None), (None, None)], 
('p7', 'h105'): ['T', ('p10', 'h105'), ('V._chalybeata_W.', 'L._senegala_rhodopsis')], 
('p120', 'L._sanguinodorsalis'): ['T', ('V._maryae', 'L._sanguinodorsalis'), ('V._camerunensis', 'L._rara')], 
('V._larvaticola', 'C._monteiri'): ['C', (None, None), (None, None)], 
('V._obtusa', 'P._afra'): ['C', (None, None), (None, None)], 
('V._regia', 'G._granatia'): ['C', (None, None), (None, None)], 
('V._purpurascens', 'L._rhodopareia'): ['C', (None, None), (None, None)], 
('p12', 'L._sanguinodorsalis'): ['T', ('p15', 'L._sanguinodorsalis'), ('p118', 'h1')], 
('V._fischeri', 'G._ianthinogaster'): ['C', (None, None), (None, None)], 
('p37', 'h83'): ['S', ('V._interjecta', 'P._phoenicoptera'), ('V._togoensis', 'P._hypogrammica')]}


H = {('h9', 'h8'): ('h9', 'h8', ('h8', 'h5'), ('h8', 'h7')), 
('h9', 'h6'): ('h9', 'h6', ('h6', 'h1'), ('h6', 'h2')), 
('h7', 'h4'): ('h7', 'h4', None, None), 
('h8', 'h7'): ('h8', 'h7', ('h7', 'h3'), ('h7', 'h4')), 
'hTop': ('Top', 'h9', ('h9', 'h8'), ('h9', 'h6')), 
('h6', 'h1'): ('h6', 'h1', None, None), 
('h8', 'h5'): ('h8', 'h5', None, None), 
('h7', 'h3'): ('h7', 'h3', None, None), 
('h6', 'h2'): ('h6', 'h2', None, None)}

P = {('p8', 'p7'): ('p8', 'p7', ('p7', 'p3'), ('p7', 'p4')), 
('p9', 'p6'): ('p9', 'p6', ('p6', 'p1'), ('p6', 'p2')), 
('p8', 'p5'): ('p8', 'p5', None, None), 
('p9', 'p8'): ('p9', 'p8', ('p8', 'p5'), ('p8', 'p7')), 
('p7', 'p4'): ('p7', 'p4', None, None), 
('p6', 'p1'): ('p6', 'p1', None, None), 
('p7', 'p3'): ('p7', 'p3', None, None), 
'pTop': ('Top', 'p9', ('p9', 'p8'), ('p9', 'p6')), 
('p6', 'p2'): ('p6', 'p2', None, None)}

phi = {'p2': 'h4', 'p3': 'h2', 'p1': 'h1', 'p4': 'h3', 'p5': 'h5'}

test7tree data: 
DTL = {('p8', 'h2'): [['T', ('p7', 'h2'), ('p5', 'h5'), 0.5], 2], 
('p4', 'h3'): [['C', (None, None), (None, None), 1.0], 0], 
('p5', 'h5'): [['C', (None, None), (None, None), 1.0], 0], 
('p7', 'h3'): [['T', ('p4', 'h3'), ('p3', 'h2'), 0.5], 1], 
('p7', 'h2'): [['T', ('p3', 'h2'), ('p4', 'h3'), 0.5], 1], 
('p2', 'h4'): [['C', (None, None), (None, None), 1.0], 0], 
('p1', 'h1'): [['C', (None, None), (None, None), 1.0], 0], 
('p6', 'h4'): [['T', ('p2', 'h4'), ('p1', 'h1'), 0.5], 1], 
('p3', 'h2'): [['C', (None, None), (None, None), 1.0], 0], 
('p6', 'h1'): [['T', ('p1', 'h1'), ('p2', 'h4'), 0.5], 1], 
('p9', 'h6'): [['S', ('p6', 'h1'), ('p8', 'h2'), 0.5], 3], 
('p8', 'h3'): [['T', ('p7', 'h3'), ('p5', 'h5'), 0.5], 2], 
('p9', 'h7'): [['S', ('p8', 'h3'), ('p6', 'h4'), 0.5], 3]}
H = {('h9', 'h8'): ('h9', 'h8', ('h8', 'h5'), ('h8', 'h7')), 
('h9', 'h6'): ('h9', 'h6', ('h6', 'h1'), ('h6', 'h2')), 
('h7', 'h4'): ('h7', 'h4', None, None), 
('h8', 'h7'): ('h8', 'h7', ('h7', 'h3'), ('h7', 'h4')), 
'hTop': ('Top', 'h9', ('h9', 'h8'), ('h9', 'h6')), 
('h6', 'h1'): ('h6', 'h1', None, None), 
('h8', 'h5'): ('h8', 'h5', None, None), 
('h7', 'h3'): ('h7', 'h3', None, None), 
('h6', 'h2'): ('h6', 'h2', None, None)}
P = {('p8', 'p7'): ('p8', 'p7', ('p7', 'p3'), ('p7', 'p4')), 
('p9', 'p6'): ('p9', 'p6', ('p6', 'p1'), ('p6', 'p2')), 
('p8', 'p5'): ('p8', 'p5', None, None), 
('p9', 'p8'): ('p9', 'p8', ('p8', 'p5'), ('p8', 'p7')), 
('p7', 'p4'): ('p7', 'p4', None, None), 
('p6', 'p1'): ('p6', 'p1', None, None), 
('p7', 'p3'): ('p7', 'p3', None, None), 
'pTop': ('Top', 'p9', ('p9', 'p8'), ('p9', 'p6')), 
('p6', 'p2'): ('p6', 'p2', None, None)}
phi = {'p2': 'h4', 'p3': 'h2', 'p1': 'h1', 'p4': 'h3', 'p5': 'h5'}
numRecon = 2


Greedy output:
{('p8', 'h2'): ['T', ('p7', 'h2'), ('p5', 'h5')], 
('p4', 'h3'): ['C', (None, None), (None, None)], 
('p5', 'h5'): ['C', (None, None), (None, None)], 
('p2', 'h4'): ['C', (None, None), (None, None)], 
('p1', 'h1'): ['C', (None, None), (None, None)], 
('p3', 'h2'): ['C', (None, None), (None, None)], 
('p6', 'h1'): ['T', ('p1', 'h1'), ('p2', 'h4')], 
('p9', 'h6'): ['S', ('p6', 'h1'), ('p8', 'h2')], 
('p7', 'h2'): ['T', ('p3', 'h2'), ('p4', 'h3')]} 


{('p7', 'h3'): ['T', ('p4', 'h3'), ('p3', 'h2')], 
('p4', 'h3'): ['C', (None, None), (None, None)], 
('p5', 'h5'): ['C', (None, None), (None, None)], 
('p2', 'h4'): ['C', (None, None), (None, None)], 
('p6', 'h4'): ['T', ('p2', 'h4'), ('p1', 'h1')], 
('p1', 'h1'): ['C', (None, None), (None, None)], 
('p3', 'h2'): ['C', (None, None), (None, None)], 
('p8', 'h3'): ['T', ('p7', 'h3'), ('p5', 'h5')], 
('p9', 'h7'): ['S', ('p8', 'h3'), ('p6', 'h4')]}








